---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ERROR_SOLUTIONS:
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented.'
SYNCBOT_SERVICE_CONSTRUCTORS:
  flowdock:
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdock"
  flowdockhashtag:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdockhashtag"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_3vkzx: "cha_3r7kd"
    serviceName: "front"
SYNCBOT_MAPPINGS:
  - source:
      service: "flowdock"
      flow: "rulemotion/syncbot-staging-test-flow"
      alias: "syncbot-staging-test-flow"
    destination:
      service: "front"
      flow: "inb_3vkzx"
      alias: "syncbot-staging-test-front"
  - source:
      service: "front"
      flow: "inb_3vkzx"
      alias: "syncbot-staging-test-front"
    destination:
      service: "flowdock"
      flow: "rulemotion/syncbot-staging-test-flow"
      alias: "syncbot-staging-test-flow"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "https://www.balena-cloud.com"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
  secret: "<<INJECT_SYNCBOT_SECRET>>"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
SYNCBOT_DEVOPS_FLOW:
SYNCBOT_DEVOPS_USERS:
