---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ERROR_SOLUTIONS:
  discourse:
    ^403:
      description: "permissions error"
      fixes:
        - "You should check that your username and token are correct."
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented.'
SYNCBOT_SERVICE_CONSTRUCTORS:
  flowdock:
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdock"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_1yea: "cha_1vc0"
      inb_3n6y: "cha_3gb6"
    serviceName: "front"
  discourse:
    protocol: "http"
    instance: "localhost"
    username: "testbot"
    secret: "<<INJECT_SYNCBOT_DISCOURSE_SECRET>>"
    token: "<<INJECT_SYNCBOT_DISCOURSE_TOKEN>>"
    serviceName: "discourse"
SYNCBOT_MAPPINGS:
  - source:
      service: "discourse"
      flow: "5"
      alias: "sandbox"
    destination:
      service: "flowdock"
      flow: "rulemotion/testing"
      alias: "sandbox"
      previous:
        - "testing"
  - source:
      service: "flowdock"
      flow: "rulemotion/testing"
      alias: "sandbox"
      previous:
        - "testing"
    destination:
      service: "front"
      flow: "inb_1yea"
      alias: "sandbox"
  - source:
      service: "front"
      flow: "inb_1yea"
      alias: "sandbox"
    destination:
      service: "flowdock"
      flow: "rulemotion/testing"
      alias: "sandbox"
      previous:
        - "testing"
  - source:
      service: "flowdock"
      flow: "rulemotion/testing_hubot"
      alias: "hubot"
    destination:
      service: "flowdock"
      flow: "rulemotion/testing"
      alias: "sandbox"
      previous:
        - "testing"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "https://www.balena-cloud.com"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
  secret: "<<INJECT_SYNCBOT_SECRET>>"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
SYNCBOT_DEVOPS_FLOW: "rulemotion/testing"
SYNCBOT_DEVOPS_USERS:
  - "788f2210f0e7227df13eeb5deda9a24a8dbb47099a83471f866f60a6b829d7fe"
  - "29d56e7a6f6de242f5d10bb691b03b775ca21b5bed45e2ce8524abe32ca19072"
  - "fff37675b12a23600dcda2bfe16a9f4cb001045ac2398cac1c0021e1eacc0218"
