---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ARCHIVE_STRINGS:
  - "#close"
  - "#archive"
SYNCBOT_ERROR_SOLUTIONS:
  discourse:
    ^403:
      description: "permissions error"
      fixes:
        - "Your username on all services should be a derivative of your GitHub username, try `Hubot suggest usernames`."
        - "If Discourse is still complaining then ping (at)sqweelygig."
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  front:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented. (@sqweelygig)'
SYNCBOT_MAPPINGS:
  - source:
      service: "discourse"
      flow: "42"
    destination:
      service: "flowdock"
      flow: "public-s-community"
  - source:
      service: "flowdock"
      flow: "public-s-community"
    destination:
      service: "front"
      flow: "inb_23sp"
  - source:
      service: "front"
      flow: "inb_23sp"
    destination:
      service: "flowdock"
      flow: "public-s-community"
  - source:
      service: "front"
      flow: "inb_nla"
    destination:
      service: "flowdock"
      flow: "public-s-premium"
  - source:
      service: "front"
      flow: "inb_2hvh"
    destination:
      service: "flowdock"
      flow: "r-leads"
SYNCBOT_LISTENER_CONSTRUCTORS:
  flowdock:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_23sp: "cha_20ep"
      inb_nla: "cha_20er"
      inb_2hvh: "cha_5cih"
  discourse:
    instance: "forums.resin.io"
    username: "syncbot"
    secret: "<<INJECT_SYNCBOT_DISCOURSE_SECRET>>"
    token: "<<INJECT_SYNCBOT_DISCOURSE_TOKEN>>"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "http://resin.io"
  publicity:
    hidden: "whisper"
    shown: "reply"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
