---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ARCHIVE_STRINGS:
  - "#close"
  - "#archive"
SYNCBOT_ERROR_SOLUTIONS:
  discourse:
    ^403:
      description: "permissions error"
      fixes:
        - "You should check that your username and token are correct."
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented. (at)sqweelygig'
SYNCBOT_LISTENER_CONSTRUCTORS:
  flowdock:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_1yea: "cha_1vc0"
      inb_3n6y: "cha_3gb6"
  github:
    client: "syncbot"
    authentication:
      appId: "<<INJECT_SYNCBOT_GITHUB_APP_ID>>"
      pem: "<<INJECT_SYNCBOT_GITHUB_PEM>>"
      type: 0
    path: "/github"
    webhookSecret: "<<INJECT_SYNCBOT_GITHUB_SECRET>>"
  discourse:
    protocol: "http"
    instance: "localhost"
    username: "testbot"
    secret: "<<INJECT_SYNCBOT_DISCOURSE_SECRET>>"
    token: "<<INJECT_SYNCBOT_DISCOURSE_TOKEN>>"
SYNCBOT_MAPPINGS:
  - source:
      service: "discourse"
      flow: "5"
    destination:
      service: "flowdock"
      flow: "testing"
  - source:
      service: "discourse"
      flow: "6"
    destination:
      service: "flowdock"
      flow: "testing"
  - source:
      service: "flowdock"
      flow: "testing"
    destination:
      service: "front"
      flow: "inb_1yea"
  - source:
      service: "front"
      flow: "inb_1yea"
    destination:
      service: "flowdock"
      flow: "testing"
  - source:
      service: "github"
      flow: "sqweelygig/syncbot-sandbox"
    destination:
      service: "flowdock"
      flow: "testing"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "http://resin.io"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
