---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ARCHIVE_STRINGS:
  - "#close"
  - "#archive"
SYNCBOT_ERROR_SOLUTIONS:
  discourse:
    ^403:
      description: "permissions error"
      fixes:
        - "Your username on all services should be a derivative of your GitHub username, try `Hubot suggest usernames`."
        - "If Discourse is still complaining then ping (at)sqweelygig."
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  flowdock:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  front:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented. (@sqweelygig)'
SYNCBOT_MAPPINGS:
  - source:
      service: "discourse"
      flow: "42"
      alias: "troubleshooting"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-community"
      alias: "forums"
  - source:
      service: "flowdock"
      flow: "rulemotion/public-s-community"
      alias: "forums"
    destination:
      service: "front"
      flow: "inb_23sp"
      alias: "forums"
  - source:
      service: "front"
      flow: "inb_23sp"
      alias: "forums"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-community"
      alias: "forums"
  - source:
      service: "front"
      flow: "inb_nla"
      alias: "paid"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-premium"
      alias: "premium"
  - source:
      service: "front"
      flow: "inb_2hvh"
      alias: "leads"
    destination:
      service: "flowdock"
      flow: "rulemotion/r-leads"
      alias: "leads"
  - source:
      service: "github"
      flow: "resin-io/hubot-as-mainbot"
      alias: "hubot"
    destination:
      service: "flowdock"
      flow: "rulemotion/d-bots"
      alias: "bots"
SYNCBOT_LISTENER_CONSTRUCTORS:
  github:
    client: "syncbot"
    authentication:
      appId: "<<INJECT_SYNCBOT_GITHUB_APP_ID>>"
      pem: "<<INJECT_SYNCBOT_GITHUB_PEM>>"
      type: 0
    path: "/github"
    webhookSecret: "<<INJECT_SYNCBOT_GITHUB_SECRET>>"
  flowdock:
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdock"
  flowdockhashtag:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdockhashtag"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_23sp: "cha_20ep"
      inb_nla: "cha_20er"
      inb_2hvh: "cha_5cih"
    serviceName: "front"
  discourse:
    instance: "forums.resin.io"
    username: "syncbot"
    secret: "<<INJECT_SYNCBOT_DISCOURSE_SECRET>>"
    token: "<<INJECT_SYNCBOT_DISCOURSE_TOKEN>>"
    serviceName: "discourse"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "http://resin.io"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
SYNCBOT_DEVOPS_FLOW: "resin-devops"
SYNCBOT_DEVOPS_USERS:
  - "2273d667fb262d0b3b891b80f198fa9ba9a88fe8025982030b813b33d0d4b8c6"
  - "788f2210f0e7227df13eeb5deda9a24a8dbb47099a83471f866f60a6b829d7fe"
  - "29d56e7a6f6de242f5d10bb691b03b775ca21b5bed45e2ce8524abe32ca19072"
