---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ERROR_SOLUTIONS:
  flowdock:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team PSA into r/support"
  front:
    ^Conversation has been received on multiple channels:
      description: "This issue was sent to more than one e-mail address, and SyncBot doesn't know which to reply from."
      fixes:
        - "Reply via Front"
    ^Tried loads of times to find the conversation:
      description: "There is an unusually long delay on Front indexing a conversation"
      fixes:
        - "Only the syncbot routes into Front (forums) should be affected."
        - "Replies via the Front UI should still get to the Forums thread."
        - "Replies via the Forums or Flowdock UI may result in duplicated Front threads."
        - "Keep half an eye on https://www.frontstatus.com/"
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "Keep half an eye on https://www.frontstatus.com/"
        - "If it persists put an (at)team PSA into r/support"
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented.'
SYNCBOT_MAPPINGS:
  # All threads in front/paid become threads in flowdock/support_premium
  - source:
      service: "front"
      flow: "inb_nla"
      alias: "paid"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-premium"
      alias: "premium"
      previous:
        - "public-s-premium"
  # All threads in front/leads become threads in flowdock/leads
  - source:
      service: "front"
      flow: "inb_2hvh"
      alias: "leads"
    destination:
      service: "flowdock"
      flow: "rulemotion/r-leads"
      alias: "leads"
      previous:
        - "r-leads"
  # All threads in front/revenue become threads in flowdock/sales_meta
  - source:
      service: "front"
      flow: "inb_8htn"
      alias: "revenue"
    destination:
      service: "flowdock"
      flow: "rulemotion/sales"
      alias: "sales_meta"
  # All threads in front/sales become threads in flowdock/sales
  - source:
      service: "front"
      flow: "inb_srn"
      alias: "sales"
    destination:
      service: "flowdock"
      flow: "rulemotion/s-sales"
      alias: "sales"
  # All threads in front/hello become threads in flowdock/hello
  - source:
      service: "front"
      flow: "inb_nsn"
      alias: "hello"
    destination:
      service: "flowdock"
      flow: "rulemotion/s-hello"
      alias: "hello"
SYNCBOT_SERVICE_CONSTRUCTORS:
  flowdock:
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdock"
  flowdockhashtag:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdockhashtag"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_nla: "cha_3rd3h"
      inb_2hvh: "cha_3rd59"
      inb_8htn: "cha_3rdal"
      inb_srn: "cha_3rd71"
      inb_nsn: "cha_3rd8t"
    serviceName: "front"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "https://www.balena-cloud.com"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
  secret: "<<INJECT_SYNCBOT_SECRET>>"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
SYNCBOT_DEVOPS_FLOW: "rulemotion/resin-devops"
SYNCBOT_DEVOPS_USERS:
  - "f3b480843f59c8f0200a75bc090ec4866401d0252bf09db3f404ea9b07060568"  # ab77
  - "76d03c51e9816cc281dbb2964f9a8012ba6c1c5f399333443c335ab60cdb314e"  # cmfcruz
  - "f207acf795f4949e200ea48af10991a8b7145269e3a67dcf333bf914c0d22ee3"  # jviotti
  - "6e82e5c266a7a74af3deaec9eec1da83ede13d1e3ea20418bc82fef75d517495"  # mbalamat
  - "c6df81ee1330868330ae4076bad4cdd7d41933d54c4cb72830d9ddd579da3c64"  # petrosagg
