---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ARCHIVE_STRINGS:
  - "#close"
  - "#archive"
  - "#summary"
SYNCBOT_ERROR_SOLUTIONS:
  discourse:
    ^403:
      description: "permissions error"
      fixes:
        - "Your username on all services should be a derivative of your GitHub username, try `Hubot suggest usernames`."
        - "If Discourse is still complaining then ping (at)sqweelygig."
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  flowdock:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  front:
    ^Conversation has been received on multiple channels:
      description: "This issue was sent to more than one e-mail address, and SyncBot doesn't know which to reply from."
      fixes:
        - "Reply via Front"
        - "@sqweelygig is monitoring to see how frequently we experience this issue."
    ^Tried loads of times to find the conversation:
      description: "There is an unusually long delay on Front indexing a conversation"
      fixes:
        - "Only the syncbot routes into Front (forums) should be affected."
        - "Replies via the Front UI should still get to the Forums thread."
        - "Replies via the Forums or Flowdock UI may result in duplicated Front threads."
        - "Keep half an eye on https://www.frontstatus.com/"
        - "Ping (at)sqweelygig if anything doesn't fit in the above pattern."
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "Keep half an eye on https://www.frontstatus.com/"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented. (@sqweelygig)'
SYNCBOT_MAPPINGS:
  # All threads in discourse/troubleshooting become threads in flowdock/support_forums
  - source:
      service: "discourse"
      flow: "42"
      alias: "troubleshooting"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-community"
      alias: "forums"
      previous:
        - "public-s-community"
  # All threads in flowdock/support_forums become threads in front/forums
  - source:
      service: "flowdock"
      flow: "rulemotion/public-s-community"
      alias: "forums"
      previous:
        - "public-s-community"
    destination:
      service: "front"
      flow: "inb_23sp"
      alias: "forums"
  # All threads in front/forums become threads in flowdock/support_forums
  - source:
      service: "front"
      flow: "inb_23sp"
      alias: "forums"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-community"
      alias: "forums"
      previous:
        - "public-s-community"
  # All threads in front/paid become threads in flowdock/support_premium
  - source:
      service: "front"
      flow: "inb_nla"
      alias: "paid"
    destination:
      service: "flowdock"
      flow: "rulemotion/public-s-premium"
      alias: "premium"
      previous:
        - "public-s-premium"
  # All threads in front/leads become threads in flowdock/leads
  - source:
      service: "front"
      flow: "inb_2hvh"
      alias: "leads"
    destination:
      service: "flowdock"
      flow: "rulemotion/r-leads"
      alias: "leads"
      previous:
        - "r-leads"
  # All threads in front/revenue become threads in flowdock/sales_meta
  - source:
      service: "front"
      flow: "inb_8htn"
      alias: "revenue"
    destination:
      service: "flowdock"
      flow: "rulemotion/sales"
      alias: "sales_meta"
  # All threads in github/hubot become threads in flowdock/bots
  - source:
      service: "github"
      flow: "resin-io/hubot-as-mainbot"
      alias: "hubot"
    destination:
      service: "flowdock"
      flow: "rulemotion/d-bots"
      alias: "bots"
      previous:
        - "d-bots"
  # All threads in front/p become threads in flowdock/p
  - source:
      service: "front"
      flow: "inb_67mx"
    destination:
      service: "flowdock"
      flow: "resinio-collaborations/p_colab_flow"
  # All threads in front/fin become threads in flowdock/support_fin
  - source:
      service: "front"
      flow: "inb_8go3"
      alias: "fin"
    destination:
      service: "flowdock"
      flow: "rulemotion/s-support_fin"
      alias: "fin"
  # All threads in forums/fin become threads in flowdock/support_fin
  - source:
      service: "discourse"
      flow: "45"
      alias: "fin"
    destination:
      service: "flowdock"
      flow: "rulemotion/s-support_fin"
      alias: "fin"
  # All threads in flowdock/support_fin become threads in front/fin
  - source:
      service: "flowdock"
      flow: "rulemotion/s-support_fin"
      alias: "fin"
    destination:
      service: "front"
      flow: "inb_8go3"
      alias: "fin"
  # All threads in front/sales become threads in flowdock/sales
  - source:
      service: "front"
      flow: "inb_srn"
      alias: "sales"
    destination:
      service: "flowdock"
      flow: "rulemotion/s-sales"
      alias: "sales"
  # All threads in front/syncbot (service outage) become threads in flowdock/support_meta
  - source:
      service: "front"
      flow: "inb_amf7"
      alias: "outage"
    destination:
      service: "flowdock"
      flow: "rulemotion/user_happiness"
      alias: "support_meta"
SYNCBOT_SERVICE_CONSTRUCTORS:
  github:
    client: "syncbot"
    authentication:
      appId: "<<INJECT_SYNCBOT_GITHUB_APP_ID>>"
      pem: "<<INJECT_SYNCBOT_GITHUB_PEM>>"
      type: 0
    path: "/github"
    webhookSecret: "<<INJECT_SYNCBOT_GITHUB_SECRET>>"
  flowdock:
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdock"
  flowdockhashtag:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
    serviceName: "flowdockhashtag"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_23sp: "cha_20ep"
      inb_nla: "cha_20er"
      inb_2hvh: "cha_5cih"
      inb_8i97: "cha_80mj"
      inb_8htn: "cha_85e3"
      inb_8go3: "cha_86t7"
      inb_1deg: "cha_9si3"
      inb_26il: "cha_9sib"
      inb_stt: "cha_9sij"
      inb_srn: "cha_9u57"
      inb_udy: "cha_9sir"
      inb_amf7: "cha_9vh"
    serviceName: "front"
  discourse:
    instance: "forums.resin.io"
    username: "syncbot"
    secret: "<<INJECT_SYNCBOT_DISCOURSE_SECRET>>"
    token: "<<INJECT_SYNCBOT_DISCOURSE_TOKEN>>"
    serviceName: "discourse"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "http://resin.io"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
  secret: "<<INJECT_SYNCBOT_SECRET>>"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
SYNCBOT_DEVOPS_FLOW: "rulemotion/resin-devops"
SYNCBOT_DEVOPS_USERS:
  - "2273d667fb262d0b3b891b80f198fa9ba9a88fe8025982030b813b33d0d4b8c6"
  - "788f2210f0e7227df13eeb5deda9a24a8dbb47099a83471f866f60a6b829d7fe"
  - "29d56e7a6f6de242f5d10bb691b03b775ca21b5bed45e2ce8524abe32ca19072"
  - "fff37675b12a23600dcda2bfe16a9f4cb001045ac2398cac1c0021e1eacc0218"
