---
SYNCBOT_ALIAS_USERS:
  - "hubot"
SYNCBOT_ARCHIVE_STRINGS:
  - "#close"
  - "#archive"
SYNCBOT_ERROR_SOLUTIONS:
  discourse:
    ^403:
      description: "permissions error"
      fixes:
        - "Your username on all services should be a derivative of your GitHub username, try `Hubot suggest usernames`."
        - "If Discourse is still complaining then ping (at)sqweelygig."
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  flowdock:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
  front:
    ^5:
      description: "Problem with their server infrastructure."
      fixes:
        - "Try again in a few minutes"
        - "If it persists put an (at)team, (at)sqweelygig PSA into r/support"
SYNCBOT_ERROR_UNDOCUMENTED: 'No fixes currently documented. (@sqweelygig)'
SYNCBOT_MAPPINGS:
  - source:
      service: "discourse"
      flow: "42"
      alias: "troubleshooting"
    destination:
      service: "flowdock"
      flow: "public-s-community"
      alias: "forums"
  - source:
      service: "flowdock"
      flow: "public-s-community"
      alias: "forums"
    destination:
      service: "front"
      flow: "inb_23sp"
      alias: "forums"
  - source:
      service: "front"
      flow: "inb_23sp"
      alias: "forums"
    destination:
      service: "flowdock"
      flow: "public-s-community"
      alias: "forums"
  - source:
      service: "front"
      flow: "inb_nla"
      alias: "paid"
    destination:
      service: "flowdock"
      flow: "public-s-premium"
      alias: "premium"
  - source:
      service: "front"
      flow: "inb_2hvh"
      alias: "leads"
    destination:
      service: "flowdock"
      flow: "r-leads"
      alias: "leads"
  - source:
      service: "github"
      flow: "resin-io/hubot-as-mainbot"
      alias: "hubot"
    destination:
      service: "flowdock"
      flow: "d-bots"
      alias: "bots"
SYNCBOT_LISTENER_CONSTRUCTORS:
  github:
    client: "syncbot"
    authentication:
      appId: "<<INJECT_SYNCBOT_GITHUB_APP_ID>>"
      pem: "<<INJECT_SYNCBOT_GITHUB_PEM>>"
      type: 0
    path: "/github"
    webhookSecret: "<<INJECT_SYNCBOT_GITHUB_SECRET>>"
  flowdock:
    organization: "rulemotion"
    token: "<<INJECT_SYNCBOT_FLOWDOCK_TOKEN>>"
  front:
    secret: "<<INJECT_SYNCBOT_FRONT_SECRET>>"
    token: "<<INJECT_SYNCBOT_FRONT_TOKEN>>"
    channelPerInbox:
      inb_23sp: "cha_20ep"
      inb_nla: "cha_20er"
      inb_2hvh: "cha_5cih"
  discourse:
    instance: "forums.resin.io"
    username: "syncbot"
    secret: "<<INJECT_SYNCBOT_DISCOURSE_SECRET>>"
    token: "<<INJECT_SYNCBOT_DISCOURSE_TOKEN>>"
SYNCBOT_METADATA_CONFIG:
  baseUrl: "http://resin.io"
  publicity:
    hidden: "whisper"
    hiddenPreferred: "murmur"
    shown: "reply"
  secret: "<<INJECT_SYNCBOT_SECRET>>"
SYNCBOT_NAME: "<<INJECT_SYNCBOT_NAME>>"
SYNCBOT_PORT: "<<INJECT_SYNCBOT_PORT>>"
